---
title: "It's time for statistics departments to start supporting their applied students"
author: "Rebecca Barter"
output:
  blogdown::html_page:
    toc: true
categories: [statistics]
date: 2020-07-30T23:13:14-05:00
type: "post" 
description: "Statistics departments are failing their applied students. In this post, I have a lot of opinions and give two pieces of advice: statistics departments need to start supporting their applied students, and they need to hire applied faculty. " 
---

I graduated with a PhD from UC Berkeley's statistics department in December. My PhD dissertation consisted of three 100% applied projects (one of which was a piece of open-source software). This is, unfortunately, incredibly rare.

Over the past few years, I've had a number of current and prospective statistics PhD students both at Berkeley and outside Berkeley get in touch with me to ask me how I made my way through a statistics PhD by working only on applied projects. My answer is always as follows: *I got lucky*. I ended up with an incredibly supportive and advisor, Bin Yu, who went out of her way to find applied projects for me, and was comfortable letting me spend time doing non-conventional things (like learn D3.js, work on my blog, and she even recruited me to be the co-author on a book on Data Science that she wanted to write based on her data science philosophy that she has developed throughout her career). I got a lot out of my PhD, and I’m incredibly grateful to Bin for her guidance. If you're interested in Bin's work, I recommend reading her paper, [Veridical Data Science](https://www.pnas.org/content/117/8/3920), which reflects the philosophy that underlies our book.

Unfortunately, my experience is definitely not the norm, even in my own department. I've had so many upsetting conversations with fellow applied stats grad students about how they feel lost and unsupported, about how they're struggling to find applied projects to work on, and when they do finally find a project, they end up having to fight to justify that their project is "statistical enough" to count towards their dissertation. I've had these conversations with students from a wide range of statistics departments, not just my own. I actually think that the Berkeley statistics department is a little better than a many other statistics departments on this front - at least at Berkeley it's *possible* to graduate with purely applied projects, even if it's not easy. 

While pretty much every statistics department is starting to realize that they need to embrace "Data Science" in order to remain up-to-date and relevant, they are often doing so in a way that is more performative than practical. They're starting data science master's programs, but these programs are often just theoretical statistics programs with a "data science" label slapped on it. They're also trying to recruit more applied students, but they aren't giving them any of the support they need to be successful. How can you expect your applied students to succeed if you don't have any truly applied faculty to guide them? And when you do have applied faculty, you don't give them tenure (because apparently they're not "furthering the field of statistics")? Who are these students going to work with? Who is going to show them that it's possible to succeed as an applied statistician in a statistics department? Unfortunately, the vast majority of statistics departments are sending a strong message that there is no such thing as success in academia for truly applied statisticians. The end result is that applied students are being brought into statistics departments, chewed up a little, and then spat out, often with a fair amount of imposter syndrome, anxiety and depression, and sadly, often without their PhDs.

