---
title: Prueba de Mantel
subtitle: ""
author: Yunier Olivera
date: `r Sys.Date()`
tag: 
   - multivarite
summary: ""
---

```{r setup, echo=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = TRUE, warning = FALSE)


library(knitr)


```

# ¿Qué es la Prueba de Mantel?

-   La Prueba de Mantel (Mantel 1967) es un análisis estadístico para evaluar la correlación entre dos matrices.

-   Las matrices deben ser de disimilitud o distancia, calculadas a partir de los mismos objetos, o sea, deben describir el mismo sistema que se está estudiando.

-   La prueba linealiza una de las porciones de la matriz, i.e. el triangulo superior o el inferior excluyendo la diagonal, y calcula la correlacion entre ambos vectores o columnas

# ¿Cuales son las asunciones?

-   Las tablas de datos para calcular ambas matrices deben haberse obtenido de forma diferente, o sea, tener variables diferentes y no ser una derivada de la otra.

-   La prueba mide relaciones lineales o monónicas, del mismo modo que lo hace la correlación de Pearson

-   Solo se deben evaluar matrices de distancia o disimilitud, no de similitud u otro tipo

# Prueba de Mantel en R

# Historia de la Prueba de Mantel
